version: '3.8'

services:
  $$cap_appname:
    build: .
    environment:
      - APP_TYPE=fastapi
      - APP_ENV=production
      - CELERY_BROKER_URL=$$cap_redis_url
      - CELERY_RESULT_BACKEND=$$cap_redis_url
      - REDIS_CACHE_URL=$$cap_redis_cache_url
      - STORAGE_PROFILE_PATH=/app/storage_profiles
      - REMOTE_API_URL=$$cap_remote_api_url
    volumes:
      - $$cap_appname-storage:/app/storage
      - $$cap_appname-uploads:/app/uploads
    depends_on:
      - $$cap_appname-redis
      - $$cap_appname-celery
    restart: unless-stopped

  $$cap_appname-celery:
    build: .
    environment:
      - APP_TYPE=celery
      - APP_ENV=production
      - CELERY_BROKER_URL=$$cap_redis_url
      - CELERY_RESULT_BACKEND=$$cap_redis_url
      - STORAGE_PROFILE_PATH=/app/storage_profiles
    volumes:
      - $$cap_appname-storage:/app/storage
      - $$cap_appname-uploads:/app/uploads
    depends_on:
      - $$cap_appname-redis
    restart: unless-stopped

  $$cap_appname-redis:
    image: redis:7.2.4-alpine
    command: redis-server --appendonly yes
    volumes:
      - $$cap_appname-redis-data:/data
    restart: unless-stopped

volumes:
  $$cap_appname-storage:
  $$cap_appname-uploads:
  $$cap_appname-redis-data:
