strategies:
   llama_vision:
      class: text_extract_api.extract.strategies.ollama.OllamaStrategy
      model: llama3.2-vision:latest
      host: https://andy-imakol.ngrok.dev/
      prompt: You are a text-extraction engine. Extract **exactly all text** from this image with no additions, no formatting changes, no commentary. Output only the raw text present on the page.
   minicpm_v:
      class: text_extract_api.extract.strategies.ollama.OllamaStrategy
      model: minicpm-v
      prompt: You are a text-extraction engine. Extract **exactly all text** from this image with no additions, no formatting changes, no commentary. Output only the raw text present on the page.
   easyocr:
      class: text_extract_api.extract.strategies.easyocr.EasyOCRStrategy
   docling:
      class: text_extract_api.extract.strategies.docling.DoclingStrategy
      model: llama3.1
      prompt: You are a text-extraction engine. Extract **exactly all text** from this image with no additions, no formatting changes, no commentary. Output only the raw text present on the page.
   remote:
      class: text_extract_api.extract.strategies.remote.RemoteStrategy
      url:
